#!/usr/bin/env bash

eslint_executable=`find -name .git -prune -o -name eslint -executable -type f -follow -print`

files=$(git diff --cached --name-only --diff-filter=M | grep '\.js$')

# Prevent ESLint help message if no files matched
if [[ ${files} = "" ]] ; then
  exit 0
fi

failed=0
for file in ${files}; do
  git show :${file} | ${eslint_executable} --stdin --stdin-filename "$file"
  if [[ $? != 0 ]] ; then
    failed=1
  fi
done;

if [[ $failed != 0 ]] ; then
  echo "🚫🚫🚫 ESLint failed, git commit denied!"
  exit $failed
fi