#!/usr/bin/env bash

files=$(git diff --cached --name-only --diff-filter=M | grep '\.js$')

# Prevent ESLint help message if no files matched
if [[ ${files} = "" ]] ; then
  exit 0
fi

failed=0
for file in ${files}; do
  git show :${file} | npx eslint --color --stdin --stdin-filename "$file"
  if [[ $? != 0 ]] ; then
    failed=1
  fi
done;

if [[ $failed != 0 ]] ; then
  echo -e "\e[31m🚫🚫🚫 ESLint failed, git commit denied!\e[39m"
  exit $failed
fi